version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest $ECR_REPO_URI:latest
  build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REPO_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing ECS task definition update to CodeDeploy
artifacts:
  files:
    - imagedefinitions.json
