version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo "Starting build phase..."
      - docker pull bazith1/my-flask-app:latest || true
      - docker build --cache-from bazith1/my-flask-app:latest -t my-flask-app:latest .
      - docker tag my-flask-app:latest bazith1/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - docker push bazith1/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Build and push successful"
artifacts:
  files:
    - k8s/*
  discard-paths: yes
