version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-flask-app:latest .
      - docker tag my-flask-app:latest <your-dockerhub-username>/my-flask-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to Docker Hub..."
      - docker push <your-dockerhub-username>/my-flask-app:latest
artifacts:
  files:
    - k8s/*
