version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo "Building Docker image..."
      - export IMAGE_TAG=$(git rev-parse --short HEAD)  # Use Git commit hash as the version tag
      - echo $IMAGE_TAG > image_tag.txt  # Save the image tag for later use
      - docker build -f src/Dockerfile -t bazith1/my-flask-app:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push bazith1/my-flask-app:$IMAGE_TAG
      - echo "Build and push successful"
artifacts:
  files:
    - image_tag.txt 
  discard-paths: yes
