version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/
      - echo "Installing pip..."
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - sudo python3 get-pip.py
      - echo "Installing jq for JSON parsing..."
      - yum install -y jq
      - echo "Installing Selenium dependencies..."
      - pip install selenium
      - echo "Downloading ChromeDriver..."
      - wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -P /tmp
      - unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
      - echo "Installing Google Chrome..."
      - yum install -y google-chrome-stable
  pre_build:
    commands:
      - echo "Preparing Terraform configurations..."
      - ls -R
      - chmod +x ./terraform/terraform-eks.sh
  build:
    commands:
      - echo "Running Terraform script..."
      - ./terraform/terraform-eks.sh
      - echo "Extracting EKS cluster details..."
      - terraform -chdir=terraform output -json > eks-cluster-output.json
      - echo "Setting up kubeconfig for EKS..."
      - aws eks --region $(jq -r '.region.value' eks-cluster-output.json) update-kubeconfig --name $(jq -r '.cluster_name.value' eks-cluster-output.json)
      - echo "Deploying Kubernetes resources..."
      - ls -R
      - kubectl apply -f ./ansible/deployment.yaml
      - kubectl apply -f ./ansible/service.yaml
  post_build:
    commands:
      - echo "Retrieving External IP or DNS for the service..."
      - kubectl get service my-service -o json | jq -r '.status.loadBalancer.ingress[0].hostname' > service_dns.txt
      - SERVICE_DNS=$(cat service_dns.txt)
      - echo "Service available at $SERVICE_DNS"
      - echo "Running Selenium End-to-End (E2E) tests..."
      - python tests/selenium_e2e_test.py --service_dns=$SERVICE_DNS
      - echo "Build and Selenium E2E testing finished."

artifacts:
  files:
    - "**/*"
  discard-paths: yes
