version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - ls -l # List the files to verify if image_tag.txt is created

  build:
    commands:
      - echo "Building Docker image with 'latest' tag..."
      - docker build -f src/Dockerfile -t bazith1/my-flask-app:latest .

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub with 'latest' tag..."
      - docker push bazith1/my-flask-app:latest
      - echo "latest" > image_tag.txt # Create image_tag.txt file
      - echo "Preserving image_tag.txt as an artifact"
      
artifacts:
  files:
    - image_tag.txt