version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/   
      - echo "Terraform installed successfully!"

  pre_build:
    commands:
      - echo "Verifying AWS CLI credentials..."
      - aws sts get-caller-identity

  build:
    commands:
      - ls -R
      - echo "Running Terraform destroy to delete the EKS cluster..."
      - chmod +x ./terraform/terraform-destroy.sh
      - ./terraform/terraform-destroy.sh

  post_build:
    commands:
      - echo "Terraform destroy execution complete."

artifacts:
  files:
    - terraform-destroy.sh
    - buildspec-terraform-destroy.yml
    - .terraform/**/*
