version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo "Using CodeBuild commit hash as image tag..."
      - export IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $IMAGE_TAG > image_tag.txt  # Save the image tag to a file
      - ls -l # List the files to verify image_tag.txt is created
      

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -f src/Dockerfile -t bazith1/my-flask-app:$IMAGE_TAG .
  
  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push bazith1/my-flask-app:$IMAGE_TAG
      - echo "Preserving image_tag.txt as an artifact"
      - cp image_tag.txt /tmp/image_tag.txt 

artifacts:
  files:
    - image_tag.txt
