AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to create ECS resources.

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 Instance type for ECS instances

  VpcID:
    Type: String
    Description: VPC ID where ECS resources will be created.

  SubnetID:
    Type: String
    Description: Subnet ID where ECS resources will be created.

Resources:

  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyECSCluster

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      VersionDescription: 1
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: ami-xxxxxxxxx  # Replace with the ECS optimized AMI ID
        SecurityGroupIds:
          - !Ref MySecurityGroup
        UserData: |
          #!/bin/bash
          echo ECS_CLUSTER=MyECSCluster >> /etc/ecs/ecs.config

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetID
      LaunchTemplate:
        LaunchTemplateName: !Ref MyLaunchTemplate
        Version: 1
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: MyECSInstance
          PropagateAtLaunch: true

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Subnets:
        - !Ref SubnetID
      SecurityGroups:
        - !Ref MySecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcID
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

Outputs:
  ALBArn:
    Description: ALB ARN
    Value: !GetAtt MyALB.Arn
