AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that links to VPC, ECS, and WAF resources.

Resources:

  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/your-bucket/vpc-stack.yaml"  # Replace with the actual URL for VPC stack
      Parameters:
        VpcCIDR: "10.0.0.0/16"

  # ECS Stack
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/your-bucket/ecs-stack.yaml"  # Replace with the actual URL for ECS stack
      Parameters:
        InstanceType: "t3.micro"
        VpcID: !GetAtt VPCStack.Outputs.VpcID
        SubnetID: !GetAtt VPCStack.Outputs.SubnetID

  # WAF Stack
  WAFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/your-bucket/waf-stack.yaml"  # Replace with the actual URL for WAF stack
      Parameters:
        ALBArn: !GetAtt ECSStack.Outputs.ALBArn

Outputs:
  VPCID:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcID

  SubnetID:
    Description: Subnet ID
    Value: !GetAtt VPCStack.Outputs.SubnetID
