AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to create WAF WebACL for ALB.

Parameters:
  ALBArn:
    Type: String
    Description: ARN of the Application Load Balancer

Resources:

  MyWAFWebACL:
    Type: AWS::WAFV2::WebACL
    Properties:
      Name: MyWAFWebACL
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Description: WAF to protect ALB
      Rules:
        - Name: AllowHTTP
          Priority: 0
          Action:
            Allow: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AllowHTTP
            SampledRequestsEnabled: true

  MyWAFWebACLAssociation:
    Type: AWS::WAFV2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ALBArn
      WebACLArn: !Ref MyWAFWebACL
