apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # Allows one more pod than the desired replicas during the update
      maxUnavailable: 1     # Allows one pod to be unavailable during the update
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: bazith1/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION  # Dynamic image tag (replace with actual tag)
        ports:
        - containerPort: 5000
