---
- name: Deploy application
  hosts: localhost
  connection: local  # Use local connection instead of SSH
  tasks:
    - name: Ensure deploy.sh is executable
      file:
        path: ./scripts/deploy.sh
        mode: u+x

    - name: Run the deploy.sh script
      command: ./scripts/deploy.sh "{{ eks_cluster_name }}"
