version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo "Preparing Terraform configurations..."
      - ls -R
      - chmod +x ./scripts/terraform-build/terraform-eks.sh
  build:
    commands:
      - echo "Running Terraform script..."
      - ./scripts/terraform-build/terraform-eks.sh
  post_build:
    commands:
      - echo "Terraform execution complete. Build finished."

artifacts:
  files:
    - "**/*"
