version: 0.2
phases:
  pre_build:
    commands:
      - echo "Setting up Terraform..."
  build:
    commands:
      - echo "Applying Terraform to create/update EKS cluster..."
      - chmod +x ./terraform-eks.sh
      - ./terraform-eks.sh
  post_build:
    commands:
      - echo "Build Complete"